/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import com.toedter.calendar.JDateChooser; 
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;// Para el JDateChooser (Calendario)
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import parte1.conexion;

/**
 *
 * @author USUARIO
 */
public class Medicamentos extends javax.swing.JPanel {
conexion cx = new conexion("bases_proyecto");
    /**
     * Creates new form Medicamentos
     */
    public Medicamentos() {
        initComponents();
    }
    public void cargarMedicamentosRecetados() {
    String idUsuarioText = txtIdUsuario.getText(); // Obtener el ID del usuario desde el JTextField

    if (idUsuarioText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el ID del usuario.");
        return;
    }

    int idUsuario = Integer.parseInt(idUsuarioText); // Convertir a entero

    // Consulta SQL mejorada para excluir medicamentos con stock 0 o "Nada"
    String query = "SELECT m.stock, m.nombre AS medicamento, h.cantidad_med AS cantidad, (m.precio * h.cantidad_med) AS total " +
                   "FROM historial_medico h " +
                   "JOIN medicamentos m ON h.medicamentos = m.id " +
                   "WHERE h.id_usuario = ? " +
                   "AND m.stock > 0 " +          // Excluir medicamentos sin stock
                   "AND m.nombre != 'Nada' " +  // Excluir "Nada"
                   "AND h.cantidad_med > 0";    // Excluir cantidades en 0

    try (Connection conn = cx.conectar();
         PreparedStatement pst = conn.prepareStatement(query)) {

        pst.setInt(1, idUsuario); // Filtrar por ID del usuario

        try (ResultSet rs = pst.executeQuery()) {
            javax.swing.table.TableModel modelo = tablaReclamos.getModel();

            if (modelo instanceof DefaultTableModel) {
                DefaultTableModel tableModel = (DefaultTableModel) modelo;
                tableModel.setRowCount(0); // Limpiar la tabla antes de actualizar

                while (rs.next()) {
                    int stock = rs.getInt("stock");
                    String medicamento = rs.getString("medicamento");
                    int cantidad = rs.getInt("cantidad");
                    int total = rs.getInt("total"); // Precio * cantidad

                    // Agregar datos a la tabla solo si son válidos
                    tableModel.addRow(new Object[]{stock, medicamento, cantidad, total});
                }
            }
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar los medicamentos recetados.");
    }
}

  
    private int obtenerIdMedicamentoDesdeNombre(String nombreMedicamento) {
    String query = "SELECT id FROM medicamentos WHERE nombre = ?";
    int idMedicamento = -1;

    try (Connection conn = cx.conectar();
         PreparedStatement pst = conn.prepareStatement(query)) {

        pst.setString(1, nombreMedicamento);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            idMedicamento = rs.getInt("id"); // Obtener el ID del medicamento
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al obtener el ID del medicamento.");
    }

    return idMedicamento;
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReclamos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        filtrar = new javax.swing.JButton();
        btnreclamar = new javax.swing.JButton();
        txtIdUsuario = new javax.swing.JTextField();

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaReclamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "stock", "Medicamento", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaReclamos);

        jPanel18.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 93, 571, 255));

        jLabel1.setText("Cedula:");
        jPanel18.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 55, -1, -1));

        filtrar.setText("Filtrar");
        filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarActionPerformed(evt);
            }
        });
        jPanel18.add(filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        btnreclamar.setText("Reclamar");
        btnreclamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreclamarActionPerformed(evt);
            }
        });
        jPanel18.add(btnreclamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 366, -1, -1));

        txtIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioActionPerformed(evt);
            }
        });
        jPanel18.add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioActionPerformed

    private void btnreclamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreclamarActionPerformed
 int filaSeleccionada = tablaReclamos.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un medicamento para reclamar.");
        return;
    }

    // Obtener valores de la fila seleccionada
    String nombreMedicamento = tablaReclamos.getValueAt(filaSeleccionada, 1).toString(); // Nombre del medicamento
    int cantidadReclamada = Integer.parseInt(tablaReclamos.getValueAt(filaSeleccionada, 2).toString()); // Cantidad

    // Obtener el ID del medicamento desde la base de datos
    int idMedicamento = obtenerIdMedicamentoDesdeNombre(nombreMedicamento);
    if (idMedicamento == -1) {
        JOptionPane.showMessageDialog(this, "Error al obtener el ID del medicamento.");
        return;
    }

    // Obtener el ID del usuario
    int idUsuario = Integer.parseInt(txtIdUsuario.getText());

    // Actualizar stock del medicamento en la tabla `medicamentos`
    String actualizarStockQuery = "UPDATE medicamentos SET stock = stock - ? WHERE id = ?";

    // Eliminar la receta de la tabla `historial_medico`
    String eliminarRecetaQuery = "DELETE FROM historial_medico WHERE id_usuario = ? AND medicamentos = ? AND cantidad_med = ? LIMIT 1";

    try (Connection conn = cx.conectar();
         PreparedStatement pstUpdateStock = conn.prepareStatement(actualizarStockQuery);
         PreparedStatement pstDeleteReceta = conn.prepareStatement(eliminarRecetaQuery)) {

        // Actualizar stock
        pstUpdateStock.setInt(1, cantidadReclamada);
        pstUpdateStock.setInt(2, idMedicamento);
        pstUpdateStock.executeUpdate();

        // Eliminar receta del historial
        pstDeleteReceta.setInt(1, idUsuario);
        pstDeleteReceta.setInt(2, idMedicamento);
        pstDeleteReceta.setInt(3, cantidadReclamada);
        pstDeleteReceta.executeUpdate();

        JOptionPane.showMessageDialog(this, "Medicamento reclamado con éxito.");

        // Actualizar la tabla después del reclamo
        cargarMedicamentosRecetados();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al reclamar el medicamento.");
        
    }
     
    }//GEN-LAST:event_btnreclamarActionPerformed

    private void filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarActionPerformed
       cargarMedicamentosRecetados();
    }//GEN-LAST:event_filtrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreclamar;
    private javax.swing.JButton filtrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReclamos;
    private javax.swing.JTextField txtIdUsuario;
    // End of variables declaration//GEN-END:variables
}
